In [1]:
df = catalog.load('model_data')

[12/23/23 17:41:27] INFO     Loading data from 'model_data' (CSVDataSet)...                     ]8;id=369947;file:///Users/air/Desktop/BetaStar/env/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=144454;file:///Users/air/Desktop/BetaStar/env/lib/python3.10/site-packages/kedro/io/data_catalog.py#345\345]8;;\

In [2]:
df.columns

Index(['node_id', 'target', 'participation', 'in_mod_deg', 'beta_star',
       'edge_contr', 'cada', 'kl', 'l1', 'l2',
       ...
       'emb_struc2vec_7', 'emb_struc2vec_8', 'emb_struc2vec_9',
       'emb_struc2vec_10', 'emb_struc2vec_11', 'emb_struc2vec_12',
       'emb_struc2vec_13', 'emb_struc2vec_14', 'emb_struc2vec_15',
       'emb_struc2vec_16'],
      dtype='object', length=103)

In [3]:
x_tr = catalog.load('X_train_linear')
x_te = catalog.load('X_test_linear')

[12/23/23 17:41:56] INFO     Loading data from 'X_train_linear' (ParquetDataSet)...             ]8;id=453181;file:///Users/air/Desktop/BetaStar/env/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=198698;file:///Users/air/Desktop/BetaStar/env/lib/python3.10/site-packages/kedro/io/data_catalog.py#345\345]8;;\

                    INFO     Loading data from 'X_test_linear' (ParquetDataSet)...              ]8;id=228742;file:///Users/air/Desktop/BetaStar/env/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=492945;file:///Users/air/Desktop/BetaStar/env/lib/python3.10/site-packages/kedro/io/data_catalog.py#345\345]8;;\

In [4]:
params = catalog.load('parameters')

[12/23/23 17:42:00] INFO     Loading data from 'parameters' (MemoryDataset)...                  ]8;id=378123;file:///Users/air/Desktop/BetaStar/env/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=942594;file:///Users/air/Desktop/BetaStar/env/lib/python3.10/site-packages/kedro/io/data_catalog.py#345\345]8;;\

In [5]:
params

{
    'env': 'x3_o1000',
    'emb_prefix': 'emb',
    'test_features': ['participation', 'in_mod_deg'],
    'embeddings': ['node2vec', 'struc2vec'],
    'node2vec': {
        'dimensions': 16,
        'walk_length': 50,
        'num_walks': 10,
        'p': 1,
        'q': 1,
        'workers': 4,
        'seed': 123
    },
    'grid': {'search': True, 'p': [1, 2], 'q': [1, 2]},
    'test_size': 0.3,
    'log_reg': {
        'penalty': 'l2',
        'C': 1.0,
        'class_weight': 'balanced',
        'solver': 'lbfgs',
        'max_iter': 1000,
        'fit_intercept': True,
        'random_state': 2023,
        'n_jobs': -1
    },
    'random_forest': {
        'n_estimators': 1000,
        'criterion': 'gini',
        'n_jobs': -1,
        'random_state': 2023,
        'max_depth': 10,
        'min_samples_split': 2,
        'min_samples_leaf': 1
    },
    'lightgbm': {
        'learning_rate': 0.1,
        'objective': 'binary',
        'boosting': 'gbdt',
        'early_stopping_rounds': 10,
        'force_col_wise': True,
        'metric': ['binary_logloss', 'auc'],
        'bagging_seed': 2023
    },
    'xgboost': {
        'booster': 'gbtree',
        'random_state': 2023,
        'objective': 'binary:logistic',
        'base_score': 0.5,
        'verbosity': 1,
        'n_jobs': -1,
        'eval_metric': 'auc',
        'seed': 2023,
        'early_stopping_rounds': 15
    },
    'cutoffs': [0.01, 0.05, 0.1],
    'permutation_importance': {'n_repeat': 50, 'random_state': 2023},
    'lin_reg': {'fit_intercept': True, 'n_jobs': -1},
    'ridge': {'alpha': 1.0, 'fit_intercept': True, 'solver': 'auto', 'random_state': 2023},
    'random_forest_reg': {
        'n_estimators': 1000,
        'criterion': 'squared_error',
        'max_depth': 10,
        'min_samples_split': 2,
        'min_samples_leaf': 1,
        'n_jobs': -1,
        'random_state': 2023
    },
    'xgboost_reg': {
        'n_estimators': 1000,
        'max_depth': 10,
        'learning_rate': 0.1,
        'verbosity': 1,
        'n_jobs': -1,
        'random_state': 2023,
        'eval_metric': 'rmse'
    },
    'lightgbm_reg': {
        'boosting': 'gbdt',
        'objective': 'regression',
        'num_leaves': 10,
        'metric': ['l2', 'l1'],
        'n_jobs': -1
    }
}

In [6]:
all_features = x_tr.columns.tolist()

In [7]:
all_features

[
    'participation',
    'in_mod_deg',
    'beta_star',
    'edge_contr',
    'cada',
    'kl',
    'l1',
    'l2',
    'hd',
    'kl2',
    'l12',
    'l22',
    'hd2',
    'lcc',
    'bc',
    'dc',
    'ndc',
    'cc',
    'ec',
    'eccen',
    'core',
    'emb_node2vec_p1q1_0',
    'emb_node2vec_p1q1_1',
    'emb_node2vec_p1q1_2',
    'emb_node2vec_p1q1_3',
    'emb_node2vec_p1q1_4',
    'emb_node2vec_p1q1_5',
    'emb_node2vec_p1q1_6',
    'emb_node2vec_p1q1_7',
    'emb_node2vec_p1q1_8',
    'emb_node2vec_p1q1_9',
    'emb_node2vec_p1q1_10',
    'emb_node2vec_p1q1_11',
    'emb_node2vec_p1q1_12',
    'emb_node2vec_p1q1_13',
    'emb_node2vec_p1q1_14',
    'emb_node2vec_p1q1_15',
    'emb_node2vec_p1q2_0',
    'emb_node2vec_p1q2_1',
    'emb_node2vec_p1q2_2',
    'emb_node2vec_p1q2_3',
    'emb_node2vec_p1q2_4',
    'emb_node2vec_p1q2_5',
    'emb_node2vec_p1q2_6',
    'emb_node2vec_p1q2_7',
    'emb_node2vec_p1q2_8',
    'emb_node2vec_p1q2_9',
    'emb_node2vec_p1q2_10',
    'emb_node2vec_p1q2_11',
    'emb_node2vec_p1q2_12',
    'emb_node2vec_p1q2_13',
    'emb_node2vec_p1q2_14',
    'emb_node2vec_p1q2_15',
    'emb_node2vec_p2q1_0',
    'emb_node2vec_p2q1_1',
    'emb_node2vec_p2q1_2',
    'emb_node2vec_p2q1_3',
    'emb_node2vec_p2q1_4',
    'emb_node2vec_p2q1_5',
    'emb_node2vec_p2q1_6',
    'emb_node2vec_p2q1_7',
    'emb_node2vec_p2q1_8',
    'emb_node2vec_p2q1_9',
    'emb_node2vec_p2q1_10',
    'emb_node2vec_p2q1_11',
    'emb_node2vec_p2q1_12',
    'emb_node2vec_p2q1_13',
    'emb_node2vec_p2q1_14',
    'emb_node2vec_p2q1_15',
    'emb_node2vec_p2q2_0',
    'emb_node2vec_p2q2_1',
    'emb_node2vec_p2q2_2',
    'emb_node2vec_p2q2_3',
    'emb_node2vec_p2q2_4',
    'emb_node2vec_p2q2_5',
    'emb_node2vec_p2q2_6',
    'emb_node2vec_p2q2_7',
    'emb_node2vec_p2q2_8',
    'emb_node2vec_p2q2_9',
    'emb_node2vec_p2q2_10',
    'emb_node2vec_p2q2_11',
    'emb_node2vec_p2q2_12',
    'emb_node2vec_p2q2_13',
    'emb_node2vec_p2q2_14',
    'emb_node2vec_p2q2_15',
    'emb_struc2vec_1',
    'emb_struc2vec_2',
    'emb_struc2vec_3',
    'emb_struc2vec_4',
    'emb_struc2vec_5',
    'emb_struc2vec_6',
    'emb_struc2vec_7',
    'emb_struc2vec_8',
    'emb_struc2vec_9',
    'emb_struc2vec_10',
    'emb_struc2vec_11',
    'emb_struc2vec_12',
    'emb_struc2vec_13',
    'emb_struc2vec_14',
    'emb_struc2vec_15',
    'emb_struc2vec_16'
]

In [9]:
emb = [f for f in all_features if f.startswith(params["emb_prefix"])]

In [16]:
p=2
q=2

In [17]:
[f for f in emb if (f"p{p}q{q}" in f) or ("struc" in f)]

[
    'emb_node2vec_p2q2_0',
    'emb_node2vec_p2q2_1',
    'emb_node2vec_p2q2_2',
    'emb_node2vec_p2q2_3',
    'emb_node2vec_p2q2_4',
    'emb_node2vec_p2q2_5',
    'emb_node2vec_p2q2_6',
    'emb_node2vec_p2q2_7',
    'emb_node2vec_p2q2_8',
    'emb_node2vec_p2q2_9',
    'emb_node2vec_p2q2_10',
    'emb_node2vec_p2q2_11',
    'emb_node2vec_p2q2_12',
    'emb_node2vec_p2q2_13',
    'emb_node2vec_p2q2_14',
    'emb_node2vec_p2q2_15',
    'emb_struc2vec_1',
    'emb_struc2vec_2',
    'emb_struc2vec_3',
    'emb_struc2vec_4',
    'emb_struc2vec_5',
    'emb_struc2vec_6',
    'emb_struc2vec_7',
    'emb_struc2vec_8',
    'emb_struc2vec_9',
    'emb_struc2vec_10',
    'emb_struc2vec_11',
    'emb_struc2vec_12',
    'emb_struc2vec_13',
    'emb_struc2vec_14',
    'emb_struc2vec_15',
    'emb_struc2vec_16'
]

In [ ]:
def get_results(X_train, X_test, parameters):
    results = {"target": [], "model_name": [], "measure": [], "value": []}
    predictions = {
        "model_name": [],
        "target": [],
        "y_pred": [],
    }

    all_features = X_train.columns.tolist()
    emb = [f for f in all_features if f.startswith(parameters["emb_prefix"])]
    features = FEATURES_LIST + emb

    for target in TARGET_LIST:
        logger.info(f"Model for target: {target}")

        for model_name, linear_model, pname in MODELS:
            logger.info(f"Model: {model_name}")
            model = linear_model(X_train[features], X_train[target], parameters[pname])
            y_pred = model.predict(X_test[features])
            predictions["model_name"].append(model_name)
            predictions["target"].append(target)
            predictions["y_pred"].append(y_pred)

            for metric, func in MEASURES:
                results["model_name"].append(model_name)
                results["measure"].append(metric)
                results["target"].append(target)
                if metric == "r2_score":
                    results["value"].append(func(X_test[target], y_pred))
                else:
                    results["value"].append(func(X_test[target], y_pred).statistic)

    return dict(results=pd.DataFrame(results), predictions=predictions)

In [ ]:
catalog.load('task1_predictions')

In [2]:
df = catalog.load('task1_results')

[12/24/23 01:52:37] INFO     Loading data from 'task1_results' (CSVDataSet)...                  ]8;id=837903;file:///Users/air/Desktop/BetaStar/env/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=297553;file:///Users/air/Desktop/BetaStar/env/lib/python3.10/site-packages/kedro/io/data_catalog.py#345\345]8;;\

In [17]:
lista = df['target'].unique()

In [19]:
for el in df['target'].unique():
    print(el)
    df1 = df[ df['target']==el ]
    for m in df1['measure'].unique():
        print(m)
        print(df1[df1['measure'] == m]['value'].min(), df1[df1['measure'] == m]['value'].mean(), df1[df1['measure'] == m]['value'].max())

cada
r2_score
0.2148726969938503 0.31096800525258594 0.4105397865417469
spearmans
0.3183412225411839 0.3935100244791953 0.4683370972465348
kendall
0.2243980941546838 0.28453165804732006 0.3465843049984301
edge_contr
r2_score
0.2452565508668541 0.3511450262930254 0.4405946709788728
spearmans
0.3352830208222839 0.4374679152440874 0.5089541637782516
kendall
0.2368124762965616 0.3194741232755489 0.3765673306664754
in_mod_deg
r2_score
0.8254509329673824 0.9079750230044874 0.9527731822700464
spearmans
0.7218306816675375 0.8327233675148842 0.9092900709373186
kendall
0.5511245968358269 0.6776522878853426 0.7720328883580273
participation
r2_score
0.225562270965684 0.3318585272056316 0.4226659119268391
spearmans
0.3360669135664726 0.43802254855416767 0.5159879133203056
kendall
0.2359414406623787 0.31542008846071634 0.3762454750845087
beta_star
r2_score
0.3648481578539383 0.4251675038050364 0.4771104950633326
spearmans
0.5249490747514541 0.5583256098384669 0.5916894072248979
kendall
0.3764253690877106 0.40190011683804044 0.4281675654473456
l1
r2_score
0.5829366642272727 0.6321448874060306 0.6622337506555316
spearmans
0.7261785559000569 0.7602056182729733 0.7934276183102684
kendall
0.5357184503527398 0.566407232860113 0.5991260020888287
l2
r2_score
0.3964130279061433 0.4620558623874826 0.5138828803691393
spearmans
0.5634836589709561 0.5928846814923533 0.6308598080468041
kendall
0.4058659683274732 0.4283670712214823 0.4597744220502722
kl
r2_score
0.7020585631724816 0.7602291534598258 0.8111334138874684
spearmans
0.8277702368686917 0.8693012265170935 0.902918865461478
kendall
0.6423761545621327 0.6874500256862041 0.7288785973595445
hd
r2_score
0.7042708456081129 0.7377691859705573 0.7678421579397438
spearmans
0.7941764159036518 0.8369008916393145 0.8767529918846283
kendall
0.6022290899366644 0.6479248577987503 0.6945490199819512
l12
r2_score
0.5051565560902445 0.6770671440563679 0.7607820749016934
spearmans
0.7394005977111774 0.8029334163614928 0.8401967844663093
kendall
0.544597977103479 0.6132326984959956 0.6535209514282538
l22
r2_score
0.4386296282245067 0.6226044393330226 0.7197377421880308
spearmans
0.64788079154231 0.7550188986470503 0.8183579575953285
kendall
0.4647891519395354 0.5649069957232369 0.6268689563187729
kl2
r2_score
0.7260670877085927 0.7958799246775117 0.8309622765865701
spearmans
0.8508987580998618 0.8871922808500162 0.9084884563774382
kendall
0.6672726464377015 0.7146543976045762 0.7451638040640041
hd2
r2_score
0.6770664786968998 0.7957881116690206 0.8415151659719803
spearmans
0.8588634896514987 0.8995148246139433 0.9172334427853234
kendall
0.6745417361342669 0.7311061840678982 0.7577580877532893

In [5]:
a = df[ df['target']=='cada']

In [13]:
a[a['measure'] == 'kendall']['value'].min(), a[a['measure'] == 'kendall']['value'].mean(), a[a['measure'] == 'kendall']['value'].max()

(0.2243980941546838, 0.28453165804732006, 0.3465843049984301)

In [10]:
a

     target        model_name    measure     value
0      cada  linear_model_1_1   r2_score  0.285915
1      cada  linear_model_1_1  spearmans  0.406988
2      cada  linear_model_1_1    kendall  0.292129
3      cada         ridge_1_1   r2_score  0.276738
4      cada         ridge_1_1  spearmans  0.401262
...     ...               ...        ...       ...
4690   cada       xgboost_7_7  spearmans  0.442274
4691   cada       xgboost_7_7    kendall  0.324352
4692   cada      lightgbm_7_7   r2_score  0.397864
4693   cada      lightgbm_7_7  spearmans  0.406459
4694   cada      lightgbm_7_7    kendall  0.293344

[375 rows x 4 columns]

In [14]:
a[a['measure'] == 'spearmans']['value'].min(),a[a['measure'] == 'spearmans']['value'].mean(),a[a['measure'] == 'spearmans']['value'].max()

(0.3183412225411839, 0.3935100244791953, 0.4683370972465348)

In [15]:
a[a['measure'] == 'r2_score']['value'].min(), a[a['measure'] == 'r2_score']['value'].mean(), a[a['measure'] == 'r2_score']['value'].max()

(0.2148726969938503, 0.31096800525258594, 0.4105397865417469)

In [21]:
b = a[a['measure'] == 'kendall']

In [24]:
 b[ b['value']>0.33]

     target   model_name  measure     value
11     cada  xgboost_1_1  kendall  0.346584
206    cada  xgboost_1_2  kendall  0.334597
401    cada  xgboost_1_3  kendall  0.331914
986    cada  xgboost_2_1  kendall  0.337888
1181   cada  xgboost_2_2  kendall  0.336558
1766   cada  xgboost_2_7  kendall  0.338856
3131   cada  xgboost_5_2  kendall  0.337657
3521   cada  xgboost_5_5  kendall  0.337058
3911   cada  xgboost_7_1  kendall  0.340272
4301   cada  xgboost_7_3  kendall  0.344725